[project]
name = "pylabrobot"
version = "0.1.6"
description = "A hardware agnostic platform for lab automation"
readme = "README.md"
requires-python = ">=3.9,<3.11"
license = {text = "MIT"}
authors = [
    {name = "PyLabRobot Contributors"}
]
keywords = ["laboratory", "automation", "liquid-handling", "robotics"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Science/Research",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
    "Topic :: Scientific/Engineering",
]
dependencies = [
    "typing_extensions",
    "ipykernel",
    "pythonnet>=3.0.5",
]

[project.optional-dependencies]
fw = ["pyserial", "pyusb", "libusb_package<=1.0.26.2"]
http = ["requests", "types-requests"]
plate_reading = ["pylibftdi"]
websockets = ["websockets==15.0.1"]
visualizer = ["websockets==15.0.1"]
opentrons = ["opentrons-http-api-client", "opentrons-shared-data"]
server = ["flask[async]"]
inheco = ["hid"]
agrow = ["pymodbus==3.6.8"]
dev = [
    "pyserial",
    "pyusb",
    "libusb_package<=1.0.26.2",
    "requests",
    "types-requests",
    "pylibftdi",
    "websockets==15.0.1",
    "opentrons-http-api-client",
    "opentrons-shared-data",
    "flask[async]",
    "hid",
    "pymodbus==3.6.8",
    "pydata-sphinx-theme",
    "myst_nb",
    "sphinx_copybutton",
    "pytest",
    "pytest-timeout",
    "mypy",
    "responses",
    "sphinx-reredirects",
    "ruff==0.2.1",
    "nbconvert",
    "sphinx-sitemap",
]
all = [
    "pyserial",
    "pyusb",
    "libusb_package<=1.0.26.2",
    "requests",
    "types-requests",
    "pylibftdi",
    "websockets==15.0.1",
    "opentrons-http-api-client",
    "opentrons-shared-data",
    "flask[async]",
    "hid",
    "pymodbus==3.6.8",
    "pydata-sphinx-theme",
    "myst_nb",
    "sphinx_copybutton",
    "pytest",
    "pytest-timeout",
    "mypy",
    "responses",
    "sphinx-reredirects",
    "ruff==0.2.1",
    "nbconvert",
    "sphinx-sitemap",
]

[project.urls]
Homepage = "https://github.com/pylabrobot/pylabrobot"
Repository = "https://github.com/pylabrobot/pylabrobot.git"
Documentation = "https://docs.pylabrobot.org"
"Bug Tracker" = "https://github.com/pylabrobot/pylabrobot/issues"

[project.scripts]
lh-server = "pylabrobot.server.liquid_handling_server:main"
plr-gui = "pylabrobot.gui.gui:main"

[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
exclude = ["tools*"]

[tool.setuptools.package-data]
pylabrobot = ["visualizer/*"]

[tool.ruff]
line-length = 100
indent-width = 2

[tool.ruff.lint.per-file-ignores]
"__init__.py" = ["F401", "F403"]

[tool.uv.workspace]
members = [
    ".",
]

[tool.uv.sources]
pylabrobot = { workspace = true, editable = true }

[dependency-groups]
dev = [
    "pylabrobot",
]

